### ISSUE TITLE
Regarding Spark Scala questions

### ISSUE THREAD

**Issue by PramodPaulWalker** [sravanapisupati/SampleDataSet#3]
pls find my below questions  ====> 

Ques1 =
Consider we have 5 folders in same path with multiple csv files inside it. What is the optimized way to load all the
csv files from different directories into Spark scala Dataframe?

example =>
  pramod is a folder in E:drive
 
  pramod => datasets => Health_Dept => data1.csv
                                    => data2.csv
  pramod => datasets => Education_Dept => School1 => data3.csv
                                                  => data4.csv
  pramod => datasets => Education_Dept => data5.csv  

Ques2 =
Consider a Spark dataframe  with an ambiguous column named as "name". How will you rename any one of the
ambiguous column?

customer.json file ===========
[{"name":"Varun",
  "product":"Headphone",
  "Delivery":{
      "name":"Varun Dhawan",
      "address":"Mumbai",
      "mob":"1234567"}},
{"name":"Shraddha",
  "product":"Hair Straightner",
  "Delivery":{
      "name":"Shraddha Kapoor",
      "address":"Bangalore",
      "mob":"5738612"}}
]

**Comment by sravanapisupati** [comment]
Hi Pramod,

For 1) 
We have an option read the directory at a time while creating a dataframe.  Provide the path until the common directory. Spark has the ability to read all the csv files inside all the subsequent folders. 

For 2)  There are some other complex method like -> (i) reading all the columns and then appending _1,_2 like this for all the columns. (ii)  get df columns as a list and for each item in list, if any element name is matching then append _1 something like this we can do. But all these overhead to the compiler. Simplest way is to rename before splitting the structType "Delivery" as shown below: 
 val df = spark.read.option("multiline", "true").json("amb_json.json")
val df1 = df.withColumnRenamed("name", "customer_name")
df1.select("*", "Delivery.* " ).drop("Delivery").show()

**Comment by PramodPaulWalker** [comment]
But how to append the column names, if we have same column names.   
If write df.select("name").show() ==> It is showing error.      
I have tried using 'withColumnRenamed', this is not working ,   

I am not getting the solutions for 2nd question,  pls have a look into it and help us.

**Comment by sravanapisupati** [comment]
val spark = SparkSession.builder().appName("Reading a JSON with ambiguous attribute").config("spark.ui.port","0").master("local").getOrCreate()
    val df = spark.read.option("multiline", "true").json("ambiguous_json.json")
    val df1 = df.withColumnRenamed("name", "customer_name")
    df1.select("*", "Delivery.*").drop("Delivery").show()
//Here you can see the name is changed to customer_name so you can select ("name") after this statement.

**Comment by PramodPaulWalker** [comment]
Now your code is working fine, I got your solutions.  Thanks Sravana 🙏🙏, for helping ,

**Comment by PramodPaulWalker** [comment]
Now your code is working fine, I got your solutions. Thanks Sravana 🙏🙏,
for helping .
